dc_ip: 192.168.56.10
domain: sevenkingdoms.local
domain_password: 8dCT-DJjgScp
domain_user: administrator
kali_ip: 10.10.10.4
max_spray_attempts: 3
opensearch_password: NCovcM7?mQU8WURvOPl
opensearch_ssh_host: 10.10.10.5
opensearch_ssh_user: wazuh
opensearch_user: admin
report_format: pdf
spray_delay_s: 5
target_ip: 192.168.56.22
verify_ssl: false
wazuh_host: 10.10.10.5
wazuh_password: NCovcM7?mQU8WURvOPl
wazuh_port: 55000
wazuh_user: wazuh
